version: '3.8'

services:
  dev:
    image: node:17.4.0-alpine3.14
    command: sh -c "yarn && yarn start:debug"
    working_dir: $PWD
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - $PWD:$PWD